### ISSUE TITLE
main.scss

### ISSUE THREAD

**Issue by jonathanphz** [shakyShane/jekyll-gulp-sass-browser-sync#13]
Is anyone else having problems watching/compiling main.scss?

Nothing happens after I edit main.scss and I get this error: invalid top-level expression  main.scss 1

I also see that main.scss is in a directory called _sass but the gulpfile.js has "gulp.src('_scss/main.scss')"

**Comment by jonathanphz** [comment]
Fixed it. main.scss should be outside _sass folder to work.

**Comment by Faltuhaisab** [comment]
i am having same issue @jonathanphz . the solution you gave is not working do you have any other alternative to solve this problem. i m using windows 8.1
