### ISSUE TITLE
Build Failure 

### ISSUE THREAD

**Issue by TreBey** [shakyShane/jekyll-gulp-sass-browser-sync#14]
Hi, I can't wait to use this project! I'm running Windows 8 and there is a build failure when I try to npm install. I updated Sass about a week ago, and updated rubygems today from an outdated version 2.2, but the problem still persists, I would love if someone can guide me in the right direction. Thanks!

```sh
6345 error Windows_NT 6.3.9600
6346 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
6347 error node v0.12.4
6348 error npm  v3.1.3
6349 error code ELIFECYCLE
6350 error node-sass@0.9.6 install: `node build.js`
6350 error Exit status 1
6351 error Failed at the node-sass@0.9.6 install script 'node build.js'.
6351 error This is most likely a problem with the node-sass package,
6351 error not with npm itself.
6351 error Tell the author that this fails on your system:
6351 error     node build.js
6351 error You can get their info via:
6351 error     npm owner ls node-sass
6351 error There is likely additional logging output above.
6352 verbose exit [ 1, true ]
```

**Comment by gregdoros** [comment]
Hi, i think it might be because of your package.json's dependencies. mine are:
```
    "browser-sync": "^2.8.0",
    "gulp": "^3.9.0",
    "gulp-autoprefixer": "^2.3.1",
    "gulp-jade": "^1.0.1",
    "gulp-sass": "^2.0.4"
```
you're trying installing sass package v0.9.6 which at tis moment doesn't exist, i think.

**Comment by TreBey** [comment]
Thanks for the reply! I'm not sure if I understand that then, because I only ran npm install inside of the project folder that was provided. I already have jekyll gem installed, as well as gulp globally installed. I checked my package.json file and this is what was there (no altercations by me)

  "devDependencies": {
    "gulp": "^3.8.8",
    "gulp-sass": "^0.7.3",
    "browser-sync": "^1.3.7",
    "gulp-autoprefixer": "1.0.0"
  },

**Comment by gregdoros** [comment]
paste my dependencies and run ' npm update ' inside your project.

**Comment by TreBey** [comment]
I did as you suggested, and got this error:

20430 error Windows_NT 6.3.9600
20431 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "update"
20432 error node v0.12.4
20433 error npm  v3.1.3
20434 error path C:\users\t\desktop\iambey\node_modules\foxy\node_modules\dev-ip
20435 error code ENOENT
20436 error errno -4058
20437 error enoent ENOENT, rename 'C:\users\t\desktop\iambey\node_modules\foxy\node_modules\dev-ip'
20437 error enoent This is most likely not a problem with npm itself
20437 error enoent and is related to npm not being able to find a file.
20438 verbose exit [ -4058, true ]


Then tried to run npm install, and got this error:

23420 error Windows_NT 6.3.9600
23421 error argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
23422 error node v0.12.4
23423 error npm  v3.1.3
23424 error code ELIFECYCLE
23425 error bufferutil@1.1.0 install: `node-gyp rebuild`
23425 error Exit status 1
23426 error Failed at the bufferutil@1.1.0 install script 'node-gyp rebuild'.
23426 error This is most likely a problem with the bufferutil package,
23426 error not with npm itself.
23426 error Tell the author that this fails on your system:
23426 error     node-gyp rebuild
23426 error You can get their info via:
23426 error     npm owner ls bufferutil
23426 error There is likely additional logging output above.
23427 verbose exit [ 1, true ]

**Comment by TreBey** [comment]
Also, I'm not sure if this helps, but I get an 'Error: Can't find Python executable, 'python', you can set the PYTHON env variable.'

I'm not sure what that means,

**Comment by gregdoros** [comment]
http://jekyll-windows.juthilo.com/ -> uinstall everything (with ccleaner for example) and install everything with this tutorial. make sure to add Python to your path while installing.

**Comment by TreBey** [comment]
Thanks for the link! When you say uninstall everything, you just mean from the project folder right? Would I just be able to delete the folder and start from scratch, instead of using something like ccleaner?

**Comment by gregdoros** [comment]
nope, i meant node.js, ruby etc. do everythin step by step with provided link. i know that it takes a lot of time, been there. : )

**Comment by TreBey** [comment]
oh i see lol. Okay well if it must be done, then I have no problem doing it. I'll get started on that and update back here once I try everything again. Thanks for the help!

**Comment by TreBey** [comment]
I'm following the steps from the link that you provided, but I'm not sure if installing 'Python to my path while installing' will be easily noticed. Will I have to do anything extra to get this done? Sorry, but I'm not really that knowledgeable with these things.

**Comment by TreBey** [comment]
I did the clean installs on rubygems, jekyll, gulp and node by following the resource you provided, but there was a problem: node build.js fails on my system, which was what the problem has always revolved around. The build failed at the node-sass script, which means that it's probably a problem with node-sass? 

Also, after uninstalling and reinstalling everything, there is a new problem: 'Could not load the Visual C++ Component "VCBuild.exe"

**Comment by gregdoros** [comment]
ha, i was waiting for it.  you need to install visual studio 2010...

**Comment by TreBey** [comment]
ah okay, so visual studio 2015 wont work? I already started installing that version

**Comment by gregdoros** [comment]
im not sure. it should be okey.

**Comment by TreBey** [comment]
Well, after about 1 hours of waiting for the Visual Studio 2015 to install, I rebooted my system and ran npm install in my project directory and got yet another error lol. I guess there's progress since it's a NEW error? 
![error with visual studio](https://cloud.githubusercontent.com/assets/12147635/9024437/cf8b173e-3894-11e5-8918-39d461ceb804.jpg)

**Comment by gregdoros** [comment]
1. it's still saying node-sass 0.9.6 -> haven't you changed it arleady?
2. did you to add $PATH to visual studio?

it is a progress, i went through the same. : P

**Comment by TreBey** [comment]
I didn't think that I needed to re-paste your dependencies into my folder after going through all of that, lol. If node-sass 0.9.6 isn't the correct version, I'm not sure why its installing that version into the project : / Maybe you know something about node-sass that I don't that I have been overlooking this entire time?

I didn't add $PATH to visual studio manually. I'm thinking about  uninstalling the 2015 version and going with the 2010 version like you suggested.

**Comment by gregdoros** [comment]
it's installing that version beacause it's said so. it is an old version and you have to update your dependencies, otherwise it wont work. check this: https://www.npmjs.com/package/gulp-sass

**Comment by Evgeny81** [comment]
Hi! I had a problem like this. First of all I changed dependencies to: {
    "gulp": "^3.8.11",
    "gulp-sass": "^2.0.4", //it won't accept any version above that, I don't know why
    "browser-sync": "^2.7.13",
    "gulp-autoprefixer": "2.3.1"
  },
second: uninstalled Python v3.4. As I understood , if it had version below v3, it would be ok.

After all everything had installed well.

**Comment by TreBey** [comment]
I just spent the last couple of days upgrading to windows 10 and Linux Mint. So, fresh start with the whole process on Linux! I pretty much got rid of all of the errors in the 'npm install' phase (with the previous suggestions!) except one, which has to do with 'jekyll-build' in the gulpfile.js. In the demo, right after 'gulp' is used, a browser window pops open with a pre-furbished site, so I'm hoping after this last problem is fixed I can finally start to use this thing! I haven't touched the gulpfile.js, so it's weird that the error is a not found error. Here's a picture of what it looks like:

![Uploading Screenshot from 2015-08-05 01:22:23.png…]()

Also, thanks for the suggestion Evgeny81. I'm also running gulp-sass 2.0.4, but that error is gone for me now after switching to a new OS and not dealing with Visual Studio and  blah blah blah. Now the problem is in the last phase. The culprit is the gulpfile.js: 

![Uploading Screenshot from 2015-08-05 01:34:44.png…]()

**Comment by TreBey** [comment]
Ok, it must be my bedtime. I forgot to install jekyll in the first place, haha. Problem solved and everything is working smoothly now!! =D
