### ISSUE TITLE
Question on line 59 of gulpfile.js

### ISSUE THREAD

**Issue by whatsnewsaes** [shakyShane/jekyll-gulp-sass-browser-sync#21]
would you want gulp watch to watch all .html files in the root instead of just index.html?

something like this:
`gulp.watch(['*.html', '_layouts/*.html', '_posts/*'], ['jekyll-rebuild']);`

instead of this: 
`gulp.watch(['index.html', '_layouts/*.html', '_posts/*'], ['jekyll-rebuild']);`

Love this configuration BTW!

**Comment by shakyShane** [comment]
yes, send a pull request please :)

**Comment by shakyShane** [comment]
closed via https://github.com/shakyShane/jekyll-gulp-sass-browser-sync/pull/22
