### ISSUE TITLE
Cannot Get /

### ISSUE THREAD

**Issue by sharathbangera6** [shakyShane/jekyll-gulp-sass-browser-sync#30]
Hi,

After doing all the installation work, i tried running gulp but the browser opens and shows Cannot GET /

_Site folder has only CSS files.

System : Windows 7

**Comment by Faltuhaisab** [comment]
hii @sharathbangera6  did you find the answer of your question. i m getting the same error as you mentioned

**Comment by sharathbangera6** [comment]
install jekyll inside the project folder and it will work.

**Comment by Faltuhaisab** [comment]
thanks,that worked. But now i m having another trouble i m not able to make changes through my main.scss folder in the localhost:3000 browser (like changing the background colour or like that).

**Comment by depiction** [comment]
I'm also having this issue. I already ran `sudo gem install bundler jekyll` in the project folder.
