### ISSUE TITLE
Format Error when trying to build jekyll

### ISSUE THREAD

**Issue by rsmidt** [shakyShane/jekyll-gulp-sass-browser-sync#31]

**Comment by Su7ech** [comment]
I have run into this issue as well.

**Comment by RyanCCollins** [comment]
Make that three.  Anyone find a fix?  I will update if I do.

**Comment by Spandan-Madan** [comment]
I'm having this problems as well! Anyone got a fix for it yet?

**Comment by Ankur-Marwaha** [comment]
Facing the same issue
