### ISSUE TITLE
browserSync is not a function in its newest releases

### ISSUE THREAD

**Issue by phorust** [shakyShane/jekyll-gulp-sass-browser-sync#37]
the `browserSync(...)` pattern has been replaced by `browserSync.init(...)`

pretty minor thing and pretty easy to fix, just want to make sure you guys are aware of it. if you `npm install browsersync` it will give you a version which doesn't support the old pattern.

**Comment by shakyShane** [comment]
@phorust this is not correct, the old api is still supported, it's just not recommended any more. 

Feel free to send a PR with updates :)
