### ISSUE TITLE
Possible to simplify with gulp-intermediate

### ISSUE THREAD

**Issue by robwierzbowski** [shakyShane/jekyll-gulp-sass-browser-sync#5]
To simplify / make this a little more feature rich, you might be interested in this recipe for Jekyll and gulp-intermediate: https://github.com/robwierzbowski/gulp-intermediate/blob/master/recipes.md#using-gulp-intermediate-directly

Feel free to close after you take a look, whether you decide to use or not.

**Comment by shakyShane** [comment]
@robwierzbowski - That does look cool, but I'd rather keep this boilerplate minimal. Could you send a PR with a section added to the README instead? A short explanation about why you'd want to use it & link would be great :)
