### ISSUE TITLE
Would this project add min css/js automation?

### ISSUE THREAD

**Issue by weilinzung** [shakyShane/jekyll-gulp-sass-browser-sync#52]
Would this project add min css/js automation?

thanks!

**Comment by esausilva** [comment]
Just install the following gem "jekyll-minifier" and add the below in your _config.yml, also you can exclude whatever you want. 

This gem will compress html, css, and js

```
gems:
    - jekyll-minifier
jekyll-minifier:
  exclude: ["*.min.*"]
```

**Comment by weilinzung** [comment]
nice. thanks!
